// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xuicspsekysdeehssetb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1aWNzcHNla3lzZGVlaHNzZXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MDQxNDcsImV4cCI6MjA3Mzk4MDE0N30.ABy7U9e9Jz02VaNVA7SOpBmPAlcQ3CA6nWvlXFc5ihQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});